#ifndef GUICOMPONENTLIB_GLOBAL_H
#define GUICOMPONENTLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GUICOMPONENTLIB_LIBRARY)
    #define GUICOMPONENTLIB_EXPORT Q_DECL_EXPORT
#else
    #define GUICOMPONENTLIB_EXPORT Q_DECL_IMPORT
#endif

#endif // GUICOMPONENTLIB_GLOBAL_H
